name: Deploy Project
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #it does not run on repository, its no server, it's a folder
      #that github's server/runner can access it
      - name: Get code

        #action is a custom application that performs repeated tasks
        #as opposed to a commands
        uses: actions/checkout@v3
      #ubuntu-latests has node16 installed by default, so we don't have to
      #however, I'm going to install version 18 to show how this works
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name:
          Install dependencies
          #starts in base directory
        working-directory: ./ReactApp
        run: npm ci
      - name: Run tests
        working-directory: ./ReactApp
        run: npm test
  #This build script has output files (artifacts)
  #"dist-files"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./ReactApp
        run: npm ci
      - name: Build website
        working-directory: ./ReactApp
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: ReactApp/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
        #all files available here now
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "This is where we would deploy..."
