name: Deploy Project
on: 
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #it does not run on repository, its no server, it's a folder
      #that github's server/runner can access it
      - name: Get code

        #action is a custom application that performs repeated tasks
        #as opposed to a commands
        uses: actions/checkout@v3
      #ubuntu-latests has node16 installed by default, so we don't have to
      #however, I'm going to install version 18 to show how this works
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name:
          Install dependencies
          #starts in base directory
        working-directory: ./ReactApp
        run: npm ci
      - name: Run tests
        working-directory: ./ReactApp
        run: npm test
  #This build script has output files (artifacts)
  #"dist-files"
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
    #steps is a special value with info about steps
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./ReactApp
        run: npm ci
      - name: Build website
        working-directory: ./ReactApp
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: ReactApp/dist
      - name: Publish JS filename
        id: publish
        #this echos the javascript file name of interest
        #the 'script-file' is the variable name of my STEPS value
        # >> $GITHUB_OUTPUT targets a special github file in the env
        #which writes our variable name + output to that file
        run: find ReactApp/dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
        #all files available here now
      - name: Output contents
        run: ls
      - name: Output filename
        #all these keywords are in the github docs
        run: echo "${{ needs.build.outputs.script-file}}"
      - name: Deploy
        run: echo "This is where we would deploy..."
