name: Create a comment on new issues

on:
  #this will be run whenever we open an issue
  issues:
    types: [opened]

jobs:
  comment-with-action:
    #didn't know I needed this permission, found while troubleshooting
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    #need issue ID, so we need the github project conext
      - name: "dumb github context"
        #this syntax tells github to evaluate inside the brackets
        #jq is a JSON processing tool
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
      run:
        #github cli has syntax for POST api
        gh api -X POST \
          http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
          -f body='
          Comment but from API call not action
          '
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORGANIZATION: ${{ github.event.organization.login }}
        REPOSITORY: ${{ github.event.repository.name }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
